// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package runpod

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type EnvVar struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetName returns EnvVar.Name, and is useful for accessing the field via an interface.
func (v *EnvVar) GetName() string { return v.Name }

// GetValue returns EnvVar.Value, and is useful for accessing the field via an interface.
func (v *EnvVar) GetValue() string { return v.Value }

// GetPodPod includes the requested fields of the GraphQL type Pod.
type GetPodPod struct {
	Id        string           `json:"id"`
	Name      string           `json:"name"`
	Status    string           `json:"status"`
	CostPerHr string           `json:"costPerHr"`
	Runtime   GetPodPodRuntime `json:"runtime"`
	Machine   GetPodPodMachine `json:"machine"`
}

// GetId returns GetPodPod.Id, and is useful for accessing the field via an interface.
func (v *GetPodPod) GetId() string { return v.Id }

// GetName returns GetPodPod.Name, and is useful for accessing the field via an interface.
func (v *GetPodPod) GetName() string { return v.Name }

// GetStatus returns GetPodPod.Status, and is useful for accessing the field via an interface.
func (v *GetPodPod) GetStatus() string { return v.Status }

// GetCostPerHr returns GetPodPod.CostPerHr, and is useful for accessing the field via an interface.
func (v *GetPodPod) GetCostPerHr() string { return v.CostPerHr }

// GetRuntime returns GetPodPod.Runtime, and is useful for accessing the field via an interface.
func (v *GetPodPod) GetRuntime() GetPodPodRuntime { return v.Runtime }

// GetMachine returns GetPodPod.Machine, and is useful for accessing the field via an interface.
func (v *GetPodPod) GetMachine() GetPodPodMachine { return v.Machine }

// GetPodPodMachine includes the requested fields of the GraphQL type Machine.
type GetPodPodMachine struct {
	PodHostId      string `json:"podHostId"`
	GpuCount       int    `json:"gpuCount"`
	GpuDisplayName string `json:"gpuDisplayName"`
	MemoryInGb     int    `json:"memoryInGb"`
	DiskInGb       int    `json:"diskInGb"`
}

// GetPodHostId returns GetPodPodMachine.PodHostId, and is useful for accessing the field via an interface.
func (v *GetPodPodMachine) GetPodHostId() string { return v.PodHostId }

// GetGpuCount returns GetPodPodMachine.GpuCount, and is useful for accessing the field via an interface.
func (v *GetPodPodMachine) GetGpuCount() int { return v.GpuCount }

// GetGpuDisplayName returns GetPodPodMachine.GpuDisplayName, and is useful for accessing the field via an interface.
func (v *GetPodPodMachine) GetGpuDisplayName() string { return v.GpuDisplayName }

// GetMemoryInGb returns GetPodPodMachine.MemoryInGb, and is useful for accessing the field via an interface.
func (v *GetPodPodMachine) GetMemoryInGb() int { return v.MemoryInGb }

// GetDiskInGb returns GetPodPodMachine.DiskInGb, and is useful for accessing the field via an interface.
func (v *GetPodPodMachine) GetDiskInGb() int { return v.DiskInGb }

// GetPodPodRuntime includes the requested fields of the GraphQL type Runtime.
type GetPodPodRuntime struct {
	Ports []GetPodPodRuntimePortsPort `json:"ports"`
}

// GetPorts returns GetPodPodRuntime.Ports, and is useful for accessing the field via an interface.
func (v *GetPodPodRuntime) GetPorts() []GetPodPodRuntimePortsPort { return v.Ports }

// GetPodPodRuntimePortsPort includes the requested fields of the GraphQL type Port.
type GetPodPodRuntimePortsPort struct {
	PrivatePort int    `json:"privatePort"`
	PublicPort  int    `json:"publicPort"`
	Type        string `json:"type"`
}

// GetPrivatePort returns GetPodPodRuntimePortsPort.PrivatePort, and is useful for accessing the field via an interface.
func (v *GetPodPodRuntimePortsPort) GetPrivatePort() int { return v.PrivatePort }

// GetPublicPort returns GetPodPodRuntimePortsPort.PublicPort, and is useful for accessing the field via an interface.
func (v *GetPodPodRuntimePortsPort) GetPublicPort() int { return v.PublicPort }

// GetType returns GetPodPodRuntimePortsPort.Type, and is useful for accessing the field via an interface.
func (v *GetPodPodRuntimePortsPort) GetType() string { return v.Type }

// GetPodResponse is returned by GetPod on success.
type GetPodResponse struct {
	Pod GetPodPod `json:"pod"`
}

// GetPod returns GetPodResponse.Pod, and is useful for accessing the field via an interface.
func (v *GetPodResponse) GetPod() GetPodPod { return v.Pod }

// ListGPUTypesGpuTypesGpuType includes the requested fields of the GraphQL type GpuType.
type ListGPUTypesGpuTypesGpuType struct {
	Id                 string                                 `json:"id"`
	DisplayName        string                                 `json:"displayName"`
	MemoryInGb         int                                    `json:"memoryInGb"`
	SecureSpotPrice    float64                                `json:"secureSpotPrice"`
	CommunitySpotPrice float64                                `json:"communitySpotPrice"`
	SecurePrice        float64                                `json:"securePrice"`
	CommunityPrice     float64                                `json:"communityPrice"`
	LowestPrice        ListGPUTypesGpuTypesGpuTypeLowestPrice `json:"lowestPrice"`
}

// GetId returns ListGPUTypesGpuTypesGpuType.Id, and is useful for accessing the field via an interface.
func (v *ListGPUTypesGpuTypesGpuType) GetId() string { return v.Id }

// GetDisplayName returns ListGPUTypesGpuTypesGpuType.DisplayName, and is useful for accessing the field via an interface.
func (v *ListGPUTypesGpuTypesGpuType) GetDisplayName() string { return v.DisplayName }

// GetMemoryInGb returns ListGPUTypesGpuTypesGpuType.MemoryInGb, and is useful for accessing the field via an interface.
func (v *ListGPUTypesGpuTypesGpuType) GetMemoryInGb() int { return v.MemoryInGb }

// GetSecureSpotPrice returns ListGPUTypesGpuTypesGpuType.SecureSpotPrice, and is useful for accessing the field via an interface.
func (v *ListGPUTypesGpuTypesGpuType) GetSecureSpotPrice() float64 { return v.SecureSpotPrice }

// GetCommunitySpotPrice returns ListGPUTypesGpuTypesGpuType.CommunitySpotPrice, and is useful for accessing the field via an interface.
func (v *ListGPUTypesGpuTypesGpuType) GetCommunitySpotPrice() float64 { return v.CommunitySpotPrice }

// GetSecurePrice returns ListGPUTypesGpuTypesGpuType.SecurePrice, and is useful for accessing the field via an interface.
func (v *ListGPUTypesGpuTypesGpuType) GetSecurePrice() float64 { return v.SecurePrice }

// GetCommunityPrice returns ListGPUTypesGpuTypesGpuType.CommunityPrice, and is useful for accessing the field via an interface.
func (v *ListGPUTypesGpuTypesGpuType) GetCommunityPrice() float64 { return v.CommunityPrice }

// GetLowestPrice returns ListGPUTypesGpuTypesGpuType.LowestPrice, and is useful for accessing the field via an interface.
func (v *ListGPUTypesGpuTypesGpuType) GetLowestPrice() ListGPUTypesGpuTypesGpuTypeLowestPrice {
	return v.LowestPrice
}

// ListGPUTypesGpuTypesGpuTypeLowestPrice includes the requested fields of the GraphQL type LowestPrice.
type ListGPUTypesGpuTypesGpuTypeLowestPrice struct {
	MinimumBidPrice      float64 `json:"minimumBidPrice"`
	UninterruptablePrice float64 `json:"uninterruptablePrice"`
}

// GetMinimumBidPrice returns ListGPUTypesGpuTypesGpuTypeLowestPrice.MinimumBidPrice, and is useful for accessing the field via an interface.
func (v *ListGPUTypesGpuTypesGpuTypeLowestPrice) GetMinimumBidPrice() float64 {
	return v.MinimumBidPrice
}

// GetUninterruptablePrice returns ListGPUTypesGpuTypesGpuTypeLowestPrice.UninterruptablePrice, and is useful for accessing the field via an interface.
func (v *ListGPUTypesGpuTypesGpuTypeLowestPrice) GetUninterruptablePrice() float64 {
	return v.UninterruptablePrice
}

// ListGPUTypesResponse is returned by ListGPUTypes on success.
type ListGPUTypesResponse struct {
	GpuTypes []ListGPUTypesGpuTypesGpuType `json:"gpuTypes"`
}

// GetGpuTypes returns ListGPUTypesResponse.GpuTypes, and is useful for accessing the field via an interface.
func (v *ListGPUTypesResponse) GetGpuTypes() []ListGPUTypesGpuTypesGpuType { return v.GpuTypes }

// ListPodsMyselfUser includes the requested fields of the GraphQL type User.
type ListPodsMyselfUser struct {
	Pods []ListPodsMyselfUserPodsPod `json:"pods"`
}

// GetPods returns ListPodsMyselfUser.Pods, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUser) GetPods() []ListPodsMyselfUserPodsPod { return v.Pods }

// ListPodsMyselfUserPodsPod includes the requested fields of the GraphQL type Pod.
type ListPodsMyselfUserPodsPod struct {
	Id        string                           `json:"id"`
	Name      string                           `json:"name"`
	Status    string                           `json:"status"`
	CostPerHr string                           `json:"costPerHr"`
	Runtime   ListPodsMyselfUserPodsPodRuntime `json:"runtime"`
	Machine   ListPodsMyselfUserPodsPodMachine `json:"machine"`
}

// GetId returns ListPodsMyselfUserPodsPod.Id, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPod) GetId() string { return v.Id }

// GetName returns ListPodsMyselfUserPodsPod.Name, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPod) GetName() string { return v.Name }

// GetStatus returns ListPodsMyselfUserPodsPod.Status, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPod) GetStatus() string { return v.Status }

// GetCostPerHr returns ListPodsMyselfUserPodsPod.CostPerHr, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPod) GetCostPerHr() string { return v.CostPerHr }

// GetRuntime returns ListPodsMyselfUserPodsPod.Runtime, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPod) GetRuntime() ListPodsMyselfUserPodsPodRuntime { return v.Runtime }

// GetMachine returns ListPodsMyselfUserPodsPod.Machine, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPod) GetMachine() ListPodsMyselfUserPodsPodMachine { return v.Machine }

// ListPodsMyselfUserPodsPodMachine includes the requested fields of the GraphQL type Machine.
type ListPodsMyselfUserPodsPodMachine struct {
	PodHostId      string `json:"podHostId"`
	GpuCount       int    `json:"gpuCount"`
	GpuDisplayName string `json:"gpuDisplayName"`
	MemoryInGb     int    `json:"memoryInGb"`
	DiskInGb       int    `json:"diskInGb"`
}

// GetPodHostId returns ListPodsMyselfUserPodsPodMachine.PodHostId, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPodMachine) GetPodHostId() string { return v.PodHostId }

// GetGpuCount returns ListPodsMyselfUserPodsPodMachine.GpuCount, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPodMachine) GetGpuCount() int { return v.GpuCount }

// GetGpuDisplayName returns ListPodsMyselfUserPodsPodMachine.GpuDisplayName, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPodMachine) GetGpuDisplayName() string { return v.GpuDisplayName }

// GetMemoryInGb returns ListPodsMyselfUserPodsPodMachine.MemoryInGb, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPodMachine) GetMemoryInGb() int { return v.MemoryInGb }

// GetDiskInGb returns ListPodsMyselfUserPodsPodMachine.DiskInGb, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPodMachine) GetDiskInGb() int { return v.DiskInGb }

// ListPodsMyselfUserPodsPodRuntime includes the requested fields of the GraphQL type Runtime.
type ListPodsMyselfUserPodsPodRuntime struct {
	Ports []ListPodsMyselfUserPodsPodRuntimePortsPort `json:"ports"`
}

// GetPorts returns ListPodsMyselfUserPodsPodRuntime.Ports, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPodRuntime) GetPorts() []ListPodsMyselfUserPodsPodRuntimePortsPort {
	return v.Ports
}

// ListPodsMyselfUserPodsPodRuntimePortsPort includes the requested fields of the GraphQL type Port.
type ListPodsMyselfUserPodsPodRuntimePortsPort struct {
	PrivatePort int    `json:"privatePort"`
	PublicPort  int    `json:"publicPort"`
	Type        string `json:"type"`
}

// GetPrivatePort returns ListPodsMyselfUserPodsPodRuntimePortsPort.PrivatePort, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPodRuntimePortsPort) GetPrivatePort() int { return v.PrivatePort }

// GetPublicPort returns ListPodsMyselfUserPodsPodRuntimePortsPort.PublicPort, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPodRuntimePortsPort) GetPublicPort() int { return v.PublicPort }

// GetType returns ListPodsMyselfUserPodsPodRuntimePortsPort.Type, and is useful for accessing the field via an interface.
func (v *ListPodsMyselfUserPodsPodRuntimePortsPort) GetType() string { return v.Type }

// ListPodsResponse is returned by ListPods on success.
type ListPodsResponse struct {
	Myself ListPodsMyselfUser `json:"myself"`
}

// GetMyself returns ListPodsResponse.Myself, and is useful for accessing the field via an interface.
func (v *ListPodsResponse) GetMyself() ListPodsMyselfUser { return v.Myself }

type PodRentInterruptableInput struct {
	CloudType           string   `json:"cloudType"`
	GpuCount            int      `json:"gpuCount"`
	VolumeInGb          int      `json:"volumeInGb"`
	ContainerDiskInGb   int      `json:"containerDiskInGb"`
	MinVcpuCount        int      `json:"minVcpuCount"`
	MinMemoryInGb       int      `json:"minMemoryInGb"`
	GpuTypeId           string   `json:"gpuTypeId"`
	Name                string   `json:"name"`
	ImageName           string   `json:"imageName"`
	Ports               string   `json:"ports"`
	VolumeMountPath     string   `json:"volumeMountPath"`
	Env                 []EnvVar `json:"env"`
	AllowedCudaVersions []string `json:"allowedCudaVersions"`
}

// GetCloudType returns PodRentInterruptableInput.CloudType, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetCloudType() string { return v.CloudType }

// GetGpuCount returns PodRentInterruptableInput.GpuCount, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetGpuCount() int { return v.GpuCount }

// GetVolumeInGb returns PodRentInterruptableInput.VolumeInGb, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetVolumeInGb() int { return v.VolumeInGb }

// GetContainerDiskInGb returns PodRentInterruptableInput.ContainerDiskInGb, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetContainerDiskInGb() int { return v.ContainerDiskInGb }

// GetMinVcpuCount returns PodRentInterruptableInput.MinVcpuCount, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetMinVcpuCount() int { return v.MinVcpuCount }

// GetMinMemoryInGb returns PodRentInterruptableInput.MinMemoryInGb, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetMinMemoryInGb() int { return v.MinMemoryInGb }

// GetGpuTypeId returns PodRentInterruptableInput.GpuTypeId, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetGpuTypeId() string { return v.GpuTypeId }

// GetName returns PodRentInterruptableInput.Name, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetName() string { return v.Name }

// GetImageName returns PodRentInterruptableInput.ImageName, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetImageName() string { return v.ImageName }

// GetPorts returns PodRentInterruptableInput.Ports, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetPorts() string { return v.Ports }

// GetVolumeMountPath returns PodRentInterruptableInput.VolumeMountPath, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetVolumeMountPath() string { return v.VolumeMountPath }

// GetEnv returns PodRentInterruptableInput.Env, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetEnv() []EnvVar { return v.Env }

// GetAllowedCudaVersions returns PodRentInterruptableInput.AllowedCudaVersions, and is useful for accessing the field via an interface.
func (v *PodRentInterruptableInput) GetAllowedCudaVersions() []string { return v.AllowedCudaVersions }

type PodStopInput struct {
	PodId string `json:"podId"`
}

// GetPodId returns PodStopInput.PodId, and is useful for accessing the field via an interface.
func (v *PodStopInput) GetPodId() string { return v.PodId }

type PodTerminateInput struct {
	PodId string `json:"podId"`
}

// GetPodId returns PodTerminateInput.PodId, and is useful for accessing the field via an interface.
func (v *PodTerminateInput) GetPodId() string { return v.PodId }

// RentSpotInstancePodRentInterruptablePod includes the requested fields of the GraphQL type Pod.
type RentSpotInstancePodRentInterruptablePod struct {
	Id        string                                         `json:"id"`
	Status    string                                         `json:"status"`
	CostPerHr string                                         `json:"costPerHr"`
	Machine   RentSpotInstancePodRentInterruptablePodMachine `json:"machine"`
}

// GetId returns RentSpotInstancePodRentInterruptablePod.Id, and is useful for accessing the field via an interface.
func (v *RentSpotInstancePodRentInterruptablePod) GetId() string { return v.Id }

// GetStatus returns RentSpotInstancePodRentInterruptablePod.Status, and is useful for accessing the field via an interface.
func (v *RentSpotInstancePodRentInterruptablePod) GetStatus() string { return v.Status }

// GetCostPerHr returns RentSpotInstancePodRentInterruptablePod.CostPerHr, and is useful for accessing the field via an interface.
func (v *RentSpotInstancePodRentInterruptablePod) GetCostPerHr() string { return v.CostPerHr }

// GetMachine returns RentSpotInstancePodRentInterruptablePod.Machine, and is useful for accessing the field via an interface.
func (v *RentSpotInstancePodRentInterruptablePod) GetMachine() RentSpotInstancePodRentInterruptablePodMachine {
	return v.Machine
}

// RentSpotInstancePodRentInterruptablePodMachine includes the requested fields of the GraphQL type Machine.
type RentSpotInstancePodRentInterruptablePodMachine struct {
	PodHostId      string `json:"podHostId"`
	GpuCount       int    `json:"gpuCount"`
	GpuDisplayName string `json:"gpuDisplayName"`
	MemoryInGb     int    `json:"memoryInGb"`
	DiskInGb       int    `json:"diskInGb"`
}

// GetPodHostId returns RentSpotInstancePodRentInterruptablePodMachine.PodHostId, and is useful for accessing the field via an interface.
func (v *RentSpotInstancePodRentInterruptablePodMachine) GetPodHostId() string { return v.PodHostId }

// GetGpuCount returns RentSpotInstancePodRentInterruptablePodMachine.GpuCount, and is useful for accessing the field via an interface.
func (v *RentSpotInstancePodRentInterruptablePodMachine) GetGpuCount() int { return v.GpuCount }

// GetGpuDisplayName returns RentSpotInstancePodRentInterruptablePodMachine.GpuDisplayName, and is useful for accessing the field via an interface.
func (v *RentSpotInstancePodRentInterruptablePodMachine) GetGpuDisplayName() string {
	return v.GpuDisplayName
}

// GetMemoryInGb returns RentSpotInstancePodRentInterruptablePodMachine.MemoryInGb, and is useful for accessing the field via an interface.
func (v *RentSpotInstancePodRentInterruptablePodMachine) GetMemoryInGb() int { return v.MemoryInGb }

// GetDiskInGb returns RentSpotInstancePodRentInterruptablePodMachine.DiskInGb, and is useful for accessing the field via an interface.
func (v *RentSpotInstancePodRentInterruptablePodMachine) GetDiskInGb() int { return v.DiskInGb }

// RentSpotInstanceResponse is returned by RentSpotInstance on success.
type RentSpotInstanceResponse struct {
	PodRentInterruptable RentSpotInstancePodRentInterruptablePod `json:"podRentInterruptable"`
}

// GetPodRentInterruptable returns RentSpotInstanceResponse.PodRentInterruptable, and is useful for accessing the field via an interface.
func (v *RentSpotInstanceResponse) GetPodRentInterruptable() RentSpotInstancePodRentInterruptablePod {
	return v.PodRentInterruptable
}

// StopPodPodStopPod includes the requested fields of the GraphQL type Pod.
type StopPodPodStopPod struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

// GetId returns StopPodPodStopPod.Id, and is useful for accessing the field via an interface.
func (v *StopPodPodStopPod) GetId() string { return v.Id }

// GetStatus returns StopPodPodStopPod.Status, and is useful for accessing the field via an interface.
func (v *StopPodPodStopPod) GetStatus() string { return v.Status }

// StopPodResponse is returned by StopPod on success.
type StopPodResponse struct {
	PodStop StopPodPodStopPod `json:"podStop"`
}

// GetPodStop returns StopPodResponse.PodStop, and is useful for accessing the field via an interface.
func (v *StopPodResponse) GetPodStop() StopPodPodStopPod { return v.PodStop }

// TerminatePodPodTerminatePod includes the requested fields of the GraphQL type Pod.
type TerminatePodPodTerminatePod struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

// GetId returns TerminatePodPodTerminatePod.Id, and is useful for accessing the field via an interface.
func (v *TerminatePodPodTerminatePod) GetId() string { return v.Id }

// GetStatus returns TerminatePodPodTerminatePod.Status, and is useful for accessing the field via an interface.
func (v *TerminatePodPodTerminatePod) GetStatus() string { return v.Status }

// TerminatePodResponse is returned by TerminatePod on success.
type TerminatePodResponse struct {
	PodTerminate TerminatePodPodTerminatePod `json:"podTerminate"`
}

// GetPodTerminate returns TerminatePodResponse.PodTerminate, and is useful for accessing the field via an interface.
func (v *TerminatePodResponse) GetPodTerminate() TerminatePodPodTerminatePod { return v.PodTerminate }

// __GetPodInput is used internally by genqlient
type __GetPodInput struct {
	PodId string `json:"podId"`
}

// GetPodId returns __GetPodInput.PodId, and is useful for accessing the field via an interface.
func (v *__GetPodInput) GetPodId() string { return v.PodId }

// __RentSpotInstanceInput is used internally by genqlient
type __RentSpotInstanceInput struct {
	Input PodRentInterruptableInput `json:"input"`
}

// GetInput returns __RentSpotInstanceInput.Input, and is useful for accessing the field via an interface.
func (v *__RentSpotInstanceInput) GetInput() PodRentInterruptableInput { return v.Input }

// __StopPodInput is used internally by genqlient
type __StopPodInput struct {
	Input PodStopInput `json:"input"`
}

// GetInput returns __StopPodInput.Input, and is useful for accessing the field via an interface.
func (v *__StopPodInput) GetInput() PodStopInput { return v.Input }

// __TerminatePodInput is used internally by genqlient
type __TerminatePodInput struct {
	Input PodTerminateInput `json:"input"`
}

// GetInput returns __TerminatePodInput.Input, and is useful for accessing the field via an interface.
func (v *__TerminatePodInput) GetInput() PodTerminateInput { return v.Input }

// The query executed by GetPod.
const GetPod_Operation = `
query GetPod ($podId: String!) {
	pod(input: {podId:$podId}) {
		id
		name
		status
		costPerHr
		runtime {
			ports {
				privatePort
				publicPort
				type
			}
		}
		machine {
			podHostId
			gpuCount
			gpuDisplayName
			memoryInGb
			diskInGb
		}
	}
}
`

// Query to get pod status
func GetPod(
	ctx_ context.Context,
	client_ graphql.Client,
	podId string,
) (data_ *GetPodResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetPod",
		Query:  GetPod_Operation,
		Variables: &__GetPodInput{
			PodId: podId,
		},
	}

	data_ = &GetPodResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListGPUTypes.
const ListGPUTypes_Operation = `
query ListGPUTypes {
	gpuTypes {
		id
		displayName
		memoryInGb
		secureSpotPrice
		communitySpotPrice
		securePrice
		communityPrice
		lowestPrice(input: {gpuCount:1}) {
			minimumBidPrice
			uninterruptablePrice
		}
	}
}
`

// Query to list available GPU types
func ListGPUTypes(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *ListGPUTypesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListGPUTypes",
		Query:  ListGPUTypes_Operation,
	}

	data_ = &ListGPUTypesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListPods.
const ListPods_Operation = `
query ListPods {
	myself {
		pods {
			id
			name
			status
			costPerHr
			runtime {
				ports {
					privatePort
					publicPort
					type
				}
			}
			machine {
				podHostId
				gpuCount
				gpuDisplayName
				memoryInGb
				diskInGb
			}
		}
	}
}
`

// Query to list user's pods
func ListPods(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *ListPodsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListPods",
		Query:  ListPods_Operation,
	}

	data_ = &ListPodsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by RentSpotInstance.
const RentSpotInstance_Operation = `
mutation RentSpotInstance ($input: PodRentInterruptableInput!) {
	podRentInterruptable(input: $input) {
		id
		status
		costPerHr
		machine {
			podHostId
			gpuCount
			gpuDisplayName
			memoryInGb
			diskInGb
		}
	}
}
`

// Mutation to rent a spot instance
func RentSpotInstance(
	ctx_ context.Context,
	client_ graphql.Client,
	input PodRentInterruptableInput,
) (data_ *RentSpotInstanceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "RentSpotInstance",
		Query:  RentSpotInstance_Operation,
		Variables: &__RentSpotInstanceInput{
			Input: input,
		},
	}

	data_ = &RentSpotInstanceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by StopPod.
const StopPod_Operation = `
mutation StopPod ($input: PodStopInput!) {
	podStop(input: $input) {
		id
		status
	}
}
`

// Mutation to stop a pod
func StopPod(
	ctx_ context.Context,
	client_ graphql.Client,
	input PodStopInput,
) (data_ *StopPodResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "StopPod",
		Query:  StopPod_Operation,
		Variables: &__StopPodInput{
			Input: input,
		},
	}

	data_ = &StopPodResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by TerminatePod.
const TerminatePod_Operation = `
mutation TerminatePod ($input: PodTerminateInput!) {
	podTerminate(input: $input) {
		id
		status
	}
}
`

// Mutation to terminate a pod
func TerminatePod(
	ctx_ context.Context,
	client_ graphql.Client,
	input PodTerminateInput,
) (data_ *TerminatePodResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "TerminatePod",
		Query:  TerminatePod_Operation,
		Variables: &__TerminatePodInput{
			Input: input,
		},
	}

	data_ = &TerminatePodResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
