# golangci-lint configuration for tgp-operator
# Minimal configuration for maximum compatibility

version: 2

run:
  timeout: 5m
  go: '1.24'

linters-settings:
  goimports:
    local-prefixes: github.com/solanyn/tgp-operator
  govet:
    enable:
      - shadow
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: zz_generated.deepcopy.go
      linters:
        - lll
    - path: _test\.go
      linters:
        - staticcheck
    - linters:
        - lll
      source: ^//\+kubebuilder
  max-issues-per-linter: 0
  max-same-issues: 0