extends: default

rules:
  line-length:
    max: 120
  document-start: disable
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false

ignore: |
  dist/
  bin/
  .git/
  schemas/
  flake.lock