---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tgp-operator
  namespace: tgp-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tgp-operator-secret
    template:
      data:
        PAPERSPACE_API_KEY: "{{ .PAPERSPACE_API_KEY }}"
        LAMBDA_LABS_API_KEY: "{{ .LAMBDA_LABS_API_KEY }}"
        RUNPOD_API_KEY: "{{ .RUNPOD_API_KEY }}"
        client-id: "{{ .TAILSCALE_CLIENT_ID }}"
        client-secret: "{{ .TAILSCALE_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: tailscale
    - extract:
        key: tgp-operator
