version: '3'

# Task runner for local development - aligned with CI workflows
# CI uses the same structure but with GitHub Actions native tools

includes:
  dev: .taskfiles/dev/Taskfile.yml
  test: .taskfiles/test/Taskfile.yml
  docker: .taskfiles/docker/Taskfile.yml
  chart: .taskfiles/chart/Taskfile.yml
  release: .taskfiles/release/Taskfile.yml
  lint: .taskfiles/lint/Taskfile.yml
  security: .taskfiles/security/Taskfile.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # Basic Setup
  setup:
    desc: Setup development environment
    cmds:
      - go mod download
      - go mod tidy
      - task: dev:generate
      - task: test:setup-envtest
      - echo "Setup complete! Run 'task help' for common workflows"

  help:
    desc: Show common development workflows
    cmds:
      - |
        echo "Common workflows:"
        echo "  task build          - Build the operator"
        echo "  task test           - Run all tests"
        echo "  task lint           - Run all linters" 
        echo "  task lint:fix       - Fix all auto-fixable issues"
        echo "  task security       - Run security scans"
        echo "  task ci:local       - Run full CI suite locally"
        echo ""
        echo "See 'task --list' for all available tasks"

  # Core Development Tasks (matches CI structure)
  build:
    desc: Build the operator binary
    deps: [dev:generate]
    cmds:
      - task: dev:build

  test:
    desc: Run all tests (unit + integration)
    cmds:
      - task: test:unit
      - task: test:integration

  lint:
    desc: Run all linters
    cmds:
      - task: lint:all

  lint:fix:
    desc: Auto-fix all formatting issues
    cmds:
      - task: lint:fix-all

  security:
    desc: Run security scans
    cmds:
      - task: security:all

  # CI Simulation - runs same checks as GitHub Actions
  ci:local:
    desc: Run full CI suite locally (simulates GitHub Actions)
    cmds:
      - echo "Running CI checks locally..."
      - task: lint
      - task: test
      - task: security
      - task: docker:build
      - echo "✅ All CI checks passed!"

  ci:pr:
    desc: Run PR checks locally before pushing
    cmds:
      - echo "Running PR checks..."
      - task: lint
      - task: test:unit
      - task: dev:build
      - echo "✅ PR checks passed! Ready to push."

  # Quick Commands
  fix:
    desc: Quick fix for common issues (formatting, imports, etc)
    cmds:
      - task: lint:fix

  check:
    desc: Quick check before committing
    cmds:
      - task: lint:go
      - task: test:unit

  # Deployment
  deploy:local:
    desc: Deploy to local Talos cluster
    cmds:
      - task: docker:build
      - task: test:setup-talos
      - task: chart:install
      - echo "Deployed to local Talos cluster"

  deploy:talos:
    desc: Deploy to existing Talos cluster
    cmds:
      - task: docker:build
      - task: chart:install
      - echo "Deployed to Talos cluster"