---
version: '3'
# Task runner for local development - aligned with CI workflows
# CI uses the same structure but with GitHub Actions native tools
includes:
  dev: .taskfiles/dev/Taskfile.yml
  test: .taskfiles/test/Taskfile.yml
  docker: .taskfiles/docker/Taskfile.yml
  chart: .taskfiles/chart/Taskfile.yml
  release: .taskfiles/release/Taskfile.yml
  lint: .taskfiles/lint/Taskfile.yml
  security: .taskfiles/security/Taskfile.yml
tasks:
  default:
    desc: Show available tasks
    cmds:
      - task help

  # Common aliases
  d:
    desc: Quick development cycle (alias for 'dev')
    cmds:
      - task: dev
  t:
    desc: Run unit tests (alias for 'test:unit')
    cmds:
      - task: test:unit
  f:
    desc: Fix formatting (alias for 'fix')
    cmds:
      - task: fix
  c:
    desc: Quick check (alias for 'check')
    cmds:
      - task: check

  # Basic Setup
  setup:
    desc: Setup development environment
    cmds:
      - go mod download
      - go mod tidy
      - task: dev:generate
      - task: test:setup-envtest
      - echo "Setup complete! Run 'task help' for common workflows"

  # Secrets Management
  secrets:load:
    desc: Generate .env file from 1Password secrets (if needed)
    cmds:
      - op inject -i .env.template -o .env
      - |
        echo "Generated .env file with API keys from 1Password"
        echo "Run: source .env"
        echo "Then: go test -tags=real ./test/real/..."
  test:providers:
    desc: Test providers with real API keys from 1Password (direct injection)
    cmds:
      - op run --env-file=.env.template -- go test -tags=real ./test/real/...
  test:provider:
    desc: Test a specific provider interactively with 1Password secrets (direct injection)
    vars:
      CLI_ARGS: '{{.CLI_ARGS}}'
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Usage examples:"
          echo "  task test:provider -- -provider=paperspace -action=info"
          echo "  task test:provider -- -provider=runpod -action=list -gpu-type=RTX4090"
          echo "  task test:provider -- -provider=lambdalabs -action=pricing -gpu-type=A100 -region=us-west-1"
          echo ""
          echo "Available providers: paperspace, lambdalabs, runpod"
          echo "Available actions: info, list, pricing"
        else
          op run --env-file=.env.template -- go run cmd/test-providers/main.go {{.CLI_ARGS}}
        fi
  help:
    desc: Show common development workflows
    cmds:
      - |
        echo "Most frequently used tasks:"
        echo ""
        echo "Development:"
        echo "  task dev             - Quick development cycle (build + test)"
        echo "  task build           - Build the operator"
        echo "  task test            - Run all tests"
        echo "  task check           - Quick pre-commit check"
        echo "  task fix             - Auto-fix formatting issues"
        echo ""
        echo "Provider testing:"
        echo "  task test:provider   - Test specific provider interactively"
        echo "  task test:providers  - Test all providers with real APIs"
        echo ""
        echo "CI/Quality:"
        echo "  task ci:pr           - Run PR checks locally"
        echo "  task lint            - Run all linters"
        echo "  task security        - Run security scans"
        echo ""
        echo "See 'task --list' for all available tasks"
        echo "Use 'task <tab>' for autocompletion"

  # Core Development Tasks (matches CI structure)
  build:
    desc: Build the operator binary
    deps: [dev:generate]
    cmds:
      - task: dev:build
  test:
    desc: Run all tests (unit + integration)
    cmds:
      - task: test:unit
      - task: test:integration
  lint:
    desc: Run all linters
    cmds:
      - task: lint:all
  lint:fix:
    desc: Auto-fix all formatting issues
    cmds:
      - task: lint:fix-all
  security:
    desc: Run security scans
    cmds:
      - task: security:all

  # CI Simulation - runs same checks as GitHub Actions
  ci:local:
    desc: Run full CI suite locally (simulates GitHub Actions)
    cmds:
      - echo "Running CI checks locally..."
      - task: lint
      - task: test
      - task: security
      - task: docker:build
      - echo "All CI checks passed!"
  ci:pr:
    desc: Run PR checks locally before pushing
    cmds:
      - echo "Running PR checks..."
      - task: lint
      - task: test:unit
      - task: dev:build
      - echo "PR checks passed! Ready to push."

  # Quick Commands
  dev:
    desc: Quick development cycle (generate + build + test)
    cmds:
      - task: dev:generate
      - task: dev:build
      - task: test:unit
      - echo "Development cycle complete!"
  fix:
    desc: Quick fix for common issues (formatting, imports, etc)
    cmds:
      - task: lint:fix
  check:
    desc: Quick check before committing
    cmds:
      - task: lint:go
      - task: test:unit

  # Deployment
  deploy:local:
    desc: Deploy to local Talos cluster
    cmds:
      - task: docker:build
      - task: test:setup-talos
      - task: chart:install
      - echo "Deployed to local Talos cluster"
  deploy:talos:
    desc: Deploy to existing Talos cluster
    cmds:
      - task: docker:build
      - task: chart:install
      - echo "Deployed to Talos cluster"
