---
version: '3'
vars:
  VERSION:
    sh: |
      if command -v svu >/dev/null 2>&1; then
        svu next | sed 's/^v//'
      else
        echo "0.1.0"
      fi
tasks:
  release:
    desc: Create a full release (container + chart + GitHub release)
    prompt: This will create and publish release v{{.VERSION}}. Are you sure?
    cmds:
      - echo 'Creating release v{{.VERSION}}'
      - task: validate
      - task: sync-versions
      - task: tag
      - task: docker:push-release
      - task: chart:push-oci
      - task: github-release
      - echo 'Release v{{.VERSION}} complete!'
  validate:
    desc: Run all validation before release
    cmds:
      - task: lint:all
      - task: test:unit
      - task: chart:validate
  sync-versions:
    desc: Update all version references to match svu version
    cmds:
      - echo 'Syncing version {{.VERSION}} to all files...'
      - task: :chart:sync-version
      - sed -i '' 's/--version [0-9]\+\.[0-9]\+\.[0-9]\+/--version {{.VERSION}}/g'
        README.md
      - task: changelog
      - echo 'All files updated to version {{.VERSION}}'
  changelog:
    desc: Generate or update CHANGELOG.md using git-chglog
    cmds:
      - mise exec -- git-chglog --output CHANGELOG.md
      - echo 'CHANGELOG.md updated'
  tag:
    desc: Create and push git tag for current version
    prompt: This will create git tag v{{.VERSION}} and push to GitHub. Continue?
    cmds:
      - git add chart/Chart.yaml README.md CHANGELOG.md
      - "git commit -m 'chore: bump version to v{{.VERSION}}' || echo 'No changes\
        \ to commit'"
      - git tag v{{.VERSION}}
      - git push origin main
      - git push origin v{{.VERSION}}
      - echo 'Tagged and pushed v{{.VERSION}}'
  github-release:
    desc: Create GitHub release with generated changelog
    prompt: This will create GitHub release v{{.VERSION}}. Continue?
    vars:
      CHANGELOG:
        sh: mise exec -- git-chglog --next-tag v{{.VERSION}} v{{.VERSION}}
    preconditions:
      - sh: command -v gh
        msg: 'GitHub CLI not found. Install with: brew install gh && gh auth login'
    cmds:
      - gh release create v{{.VERSION}} --title 'Release v{{.VERSION}}' --notes '{{.CHANGELOG}}'
  next-version:
    desc: Show what the next version would be based on conventional commits
    cmds:
      - echo 'Next version based on conventional commits:'
      - |
        if command -v svu >/dev/null 2>&1; then
          echo "Current: $(svu current)"
          echo "Next: $(svu next)"
        else
          echo "svu not found - install it to see semantic versions"
        fi
  current-version:
    desc: Show current version from svu
    cmds: ["echo 'Current version: {{.VERSION}}'"]
  prepare-release:
    desc: Prepare for release (sync versions but don't tag/release)
    cmds:
      - task: validate
      - task: sync-versions
      - echo 'Ready for release v{{.VERSION}}. Run task release:release when ready.'
