//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequest) DeepCopyInto(out *GPURequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequest.
func (in *GPURequest) DeepCopy() *GPURequest {
	if in == nil {
		return nil
	}
	out := new(GPURequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPURequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestList) DeepCopyInto(out *GPURequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPURequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestList.
func (in *GPURequestList) DeepCopy() *GPURequestList {
	if in == nil {
		return nil
	}
	out := new(GPURequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPURequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestSpec) DeepCopyInto(out *GPURequestSpec) {
	*out = *in
	if in.MaxHourlyPrice != nil {
		in, out := &in.MaxHourlyPrice, &out.MaxHourlyPrice
		*out = new(float64)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	in.TalosConfig.DeepCopyInto(&out.TalosConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestSpec.
func (in *GPURequestSpec) DeepCopy() *GPURequestSpec {
	if in == nil {
		return nil
	}
	out := new(GPURequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestStatus) DeepCopyInto(out *GPURequestStatus) {
	*out = *in
	if in.ProvisionedAt != nil {
		in, out := &in.ProvisionedAt, &out.ProvisionedAt
		*out = (*in).DeepCopy()
	}
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestStatus.
func (in *GPURequestStatus) DeepCopy() *GPURequestStatus {
	if in == nil {
		return nil
	}
	out := new(GPURequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosConfig) DeepCopyInto(out *TalosConfig) {
	*out = *in
	in.WireGuardConfig.DeepCopyInto(&out.WireGuardConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosConfig.
func (in *TalosConfig) DeepCopy() *TalosConfig {
	if in == nil {
		return nil
	}
	out := new(TalosConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WireGuardConfig) DeepCopyInto(out *WireGuardConfig) {
	*out = *in
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WireGuardConfig.
func (in *WireGuardConfig) DeepCopy() *WireGuardConfig {
	if in == nil {
		return nil
	}
	out := new(WireGuardConfig)
	in.DeepCopyInto(out)
	return out
}
