//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequest) DeepCopyInto(out *GPURequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequest.
func (in *GPURequest) DeepCopy() *GPURequest {
	if in == nil {
		return nil
	}
	out := new(GPURequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPURequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestList) DeepCopyInto(out *GPURequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPURequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestList.
func (in *GPURequestList) DeepCopy() *GPURequestList {
	if in == nil {
		return nil
	}
	out := new(GPURequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPURequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestSpec) DeepCopyInto(out *GPURequestSpec) {
	*out = *in
	if in.MaxHourlyPrice != nil {
		in, out := &in.MaxHourlyPrice, &out.MaxHourlyPrice
		*out = new(string)
		**out = **in
	}
	if in.MaxLifetime != nil {
		in, out := &in.MaxLifetime, &out.MaxLifetime
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	in.TalosConfig.DeepCopyInto(&out.TalosConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestSpec.
func (in *GPURequestSpec) DeepCopy() *GPURequestSpec {
	if in == nil {
		return nil
	}
	out := new(GPURequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestStatus) DeepCopyInto(out *GPURequestStatus) {
	*out = *in
	if in.ProvisionedAt != nil {
		in, out := &in.ProvisionedAt, &out.ProvisionedAt
		*out = (*in).DeepCopy()
	}
	if in.TerminationScheduledAt != nil {
		in, out := &in.TerminationScheduledAt, &out.TerminationScheduledAt
		*out = (*in).DeepCopy()
	}
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestStatus.
func (in *GPURequestStatus) DeepCopy() *GPURequestStatus {
	if in == nil {
		return nil
	}
	out := new(GPURequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleConfig) DeepCopyInto(out *TailscaleConfig) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ephemeral != nil {
		in, out := &in.Ephemeral, &out.Ephemeral
		*out = new(bool)
		**out = **in
	}
	if in.AcceptRoutes != nil {
		in, out := &in.AcceptRoutes, &out.AcceptRoutes
		*out = new(bool)
		**out = **in
	}
	if in.AdvertiseRoutes != nil {
		in, out := &in.AdvertiseRoutes, &out.AdvertiseRoutes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthKeySecretRef != nil {
		in, out := &in.AuthKeySecretRef, &out.AuthKeySecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.OperatorConfig != nil {
		in, out := &in.OperatorConfig, &out.OperatorConfig
		*out = new(TailscaleOperatorConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleConfig.
func (in *TailscaleConfig) DeepCopy() *TailscaleConfig {
	if in == nil {
		return nil
	}
	out := new(TailscaleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleConnectorSpec) DeepCopyInto(out *TailscaleConnectorSpec) {
	*out = *in
	if in.SubnetRouter != nil {
		in, out := &in.SubnetRouter, &out.SubnetRouter
		*out = new(TailscaleSubnetRouter)
		(*in).DeepCopyInto(*out)
	}
	if in.ExitNode != nil {
		in, out := &in.ExitNode, &out.ExitNode
		*out = new(bool)
		**out = **in
	}
	if in.AppConnector != nil {
		in, out := &in.AppConnector, &out.AppConnector
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleConnectorSpec.
func (in *TailscaleConnectorSpec) DeepCopy() *TailscaleConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(TailscaleConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleOperatorConfig) DeepCopyInto(out *TailscaleOperatorConfig) {
	*out = *in
	if in.ConnectorEnabled != nil {
		in, out := &in.ConnectorEnabled, &out.ConnectorEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectorSpec != nil {
		in, out := &in.ConnectorSpec, &out.ConnectorSpec
		*out = new(TailscaleConnectorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleOperatorConfig.
func (in *TailscaleOperatorConfig) DeepCopy() *TailscaleOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(TailscaleOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleSubnetRouter) DeepCopyInto(out *TailscaleSubnetRouter) {
	*out = *in
	if in.AdvertiseRoutes != nil {
		in, out := &in.AdvertiseRoutes, &out.AdvertiseRoutes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleSubnetRouter.
func (in *TailscaleSubnetRouter) DeepCopy() *TailscaleSubnetRouter {
	if in == nil {
		return nil
	}
	out := new(TailscaleSubnetRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosConfig) DeepCopyInto(out *TalosConfig) {
	*out = *in
	in.TailscaleConfig.DeepCopyInto(&out.TailscaleConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosConfig.
func (in *TalosConfig) DeepCopy() *TalosConfig {
	if in == nil {
		return nil
	}
	out := new(TalosConfig)
	in.DeepCopyInto(out)
	return out
}
