// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ImageArchitecture.
const (
	Arm64 ImageArchitecture = "arm64"
	X8664 ImageArchitecture = "x86_64"
)

// Defines values for InstanceActionUnavailableCode.
const (
	VmHasNotLaunched InstanceActionUnavailableCode = "vm-has-not-launched"
	VmIsTerminating  InstanceActionUnavailableCode = "vm-is-terminating"
	VmIsTooOld       InstanceActionUnavailableCode = "vm-is-too-old"
)

// Defines values for InstanceStatus.
const (
	Active      InstanceStatus = "active"
	Booting     InstanceStatus = "booting"
	Terminated  InstanceStatus = "terminated"
	Terminating InstanceStatus = "terminating"
	Unhealthy   InstanceStatus = "unhealthy"
)

// Defines values for NetworkProtocol.
const (
	All  NetworkProtocol = "all"
	Icmp NetworkProtocol = "icmp"
	Tcp  NetworkProtocol = "tcp"
	Udp  NetworkProtocol = "udp"
)

// Defines values for PublicRegionCode.
const (
	AsiaNortheast1 PublicRegionCode = "asia-northeast-1"
	AsiaNortheast2 PublicRegionCode = "asia-northeast-2"
	AsiaSouth1     PublicRegionCode = "asia-south-1"
	AustraliaEast1 PublicRegionCode = "australia-east-1"
	EuropeCentral1 PublicRegionCode = "europe-central-1"
	MeWest1        PublicRegionCode = "me-west-1"
	TestEast1      PublicRegionCode = "test-east-1"
	TestWest1      PublicRegionCode = "test-west-1"
	UsEast1        PublicRegionCode = "us-east-1"
	UsEast2        PublicRegionCode = "us-east-2"
	UsEast3        PublicRegionCode = "us-east-3"
	UsMidwest1     PublicRegionCode = "us-midwest-1"
	UsMidwest2     PublicRegionCode = "us-midwest-2"
	UsSouth1       PublicRegionCode = "us-south-1"
	UsSouth2       PublicRegionCode = "us-south-2"
	UsSouth3       PublicRegionCode = "us-south-3"
	UsWest1        PublicRegionCode = "us-west-1"
	UsWest2        PublicRegionCode = "us-west-2"
	UsWest3        PublicRegionCode = "us-west-3"
)

// AddSSHKeyRequest defines model for AddSSHKeyRequest.
type AddSSHKeyRequest struct {
	// Name The name of the SSH key.
	Name string `json:"name"`

	// PublicKey The public key for the SSH key.
	PublicKey *string `json:"public_key,omitempty"`
}

// ApiErrorAccountInactive defines model for ApiErrorAccountInactive.
type ApiErrorAccountInactive struct {
	// Code The unique identifier for the type of error.
	Code string `json:"code"`

	// Message A description of the error.
	Message string `json:"message"`

	// Suggestion One or more suggestions of possible ways to fix the error.
	Suggestion string `json:"suggestion"`
}

// ApiErrorFileSystemInWrongRegion defines model for ApiErrorFileSystemInWrongRegion.
type ApiErrorFileSystemInWrongRegion struct {
	// Code The unique identifier for the type of error.
	Code string `json:"code"`

	// Message A description of the error.
	Message string `json:"message"`

	// Suggestion One or more suggestions of possible ways to fix the error.
	Suggestion *string `json:"suggestion,omitempty"`
}

// ApiErrorInstanceNotFound defines model for ApiErrorInstanceNotFound.
type ApiErrorInstanceNotFound struct {
	// Code The unique identifier for the type of error.
	Code string `json:"code"`

	// Message A description of the error.
	Message string `json:"message"`

	// Suggestion One or more suggestions of possible ways to fix the error.
	Suggestion *string `json:"suggestion,omitempty"`
}

// ApiErrorInsufficientCapacity defines model for ApiErrorInsufficientCapacity.
type ApiErrorInsufficientCapacity struct {
	// Code The unique identifier for the type of error.
	Code string `json:"code"`

	// Message A description of the error.
	Message string `json:"message"`

	// Suggestion One or more suggestions of possible ways to fix the error.
	Suggestion *string `json:"suggestion,omitempty"`
}

// ApiErrorInvalidBillingAddress defines model for ApiErrorInvalidBillingAddress.
type ApiErrorInvalidBillingAddress struct {
	// Code The unique identifier for the type of error.
	Code string `json:"code"`

	// Message A description of the error.
	Message string `json:"message"`

	// Suggestion One or more suggestions of possible ways to fix the error.
	Suggestion string `json:"suggestion"`
}

// ApiErrorInvalidParameters defines model for ApiErrorInvalidParameters.
type ApiErrorInvalidParameters struct {
	// Code The unique identifier for the type of error.
	Code string `json:"code"`

	// Message A description of the error.
	Message string `json:"message"`

	// Suggestion One or more suggestions of possible ways to fix the error.
	Suggestion *string `json:"suggestion,omitempty"`
}

// ApiErrorLaunchResourceNotFound defines model for ApiErrorLaunchResourceNotFound.
type ApiErrorLaunchResourceNotFound struct {
	// Code The unique identifier for the type of error.
	Code string `json:"code"`

	// Message The resource the API was unable to find.
	Message string `json:"message"`

	// Suggestion One or more suggestions of possible ways to fix the error.
	Suggestion string `json:"suggestion"`
}

// ApiErrorQuotaExceeded defines model for ApiErrorQuotaExceeded.
type ApiErrorQuotaExceeded struct {
	// Code The unique identifier for the type of error.
	Code string `json:"code"`

	// Message A description of the error.
	Message string `json:"message"`

	// Suggestion One or more suggestions of possible ways to fix the error.
	Suggestion string `json:"suggestion"`
}

// ApiErrorUnauthorized defines model for ApiErrorUnauthorized.
type ApiErrorUnauthorized struct {
	// Code The unique identifier for the type of error.
	Code string `json:"code"`

	// Message A description of the error.
	Message string `json:"message"`

	// Suggestion One or more suggestions of possible ways to fix the error.
	Suggestion string `json:"suggestion"`
}

// EmptyResponse defines model for EmptyResponse.
type EmptyResponse = map[string]interface{}

// FilesystemMountEntry The mount point for a filesystem mounted to an instance.
type FilesystemMountEntry struct {
	// FileSystemId The id of the filesystem to mount to the instance.
	FileSystemId string `json:"file_system_id"`

	// MountPoint The absolute path indicating where on the instance the filesystem will be mounted.
	MountPoint string `json:"mount_point"`
}

// FirewallRule defines model for FirewallRule.
type FirewallRule struct {
	// Description A human-readable description of the rule.
	Description string `json:"description"`

	// PortRange An inclusive range of network ports specified as `[min, max]`.
	// Not allowed for the `icmp` protocol but required for the others.
	//
	// To specify a single port, list it twice (for example, `[22,22]`).
	PortRange *[]int          `json:"port_range,omitempty"`
	Protocol  NetworkProtocol `json:"protocol"`

	// SourceNetwork The set of source IPv4 addresses from which you want to allow inbound
	// traffic. These addresses must be specified in CIDR notation. You can
	// specify individual public IPv4 CIDR blocks such as `1.2.3.4` or
	// `1.2.3.4/32`, or you can specify `0.0.0.0/0` to allow access from any
	// address.
	//
	// This value is a string consisting of a public IPv4 address optionally
	// followed by a slash (/) and an integer mask (the network prefix).
	// If no mask is provided, the API assumes `/32` by default.
	SourceNetwork string `json:"source_network"`
}

// FirewallRulesPutRequest defines model for FirewallRulesPutRequest.
type FirewallRulesPutRequest struct {
	// Data The list of inbound firewall rules.
	Data []FirewallRule `json:"data"`
}

// GeneratedSSHKey Information about a server-generated SSH key, which can be used to access instances over
// SSH.
type GeneratedSSHKey struct {
	// Id The unique identifier (ID) of the SSH key.
	Id string `json:"id"`

	// Name The name of the SSH key.
	Name string `json:"name"`

	// PrivateKey The private key generated in the SSH key pair. Make sure to store a
	// copy of this key locally, as Lambda does not store the key server-side.
	PrivateKey string `json:"private_key"`

	// PublicKey The public key for the SSH key.
	PublicKey string `json:"public_key"`
}

// Image An available machine image in Lambda Cloud.
type Image struct {
	Architecture ImageArchitecture `json:"architecture"`

	// CreatedTime The date and time that the image was created.
	CreatedTime time.Time `json:"created_time"`

	// Description Additional information about the image.
	Description string `json:"description"`

	// Family The family the image belongs to.
	Family string `json:"family"`

	// Id The unique identifier (ID) for an image.
	Id string `json:"id"`

	// Name The human-readable identifier for an image.
	Name   string `json:"name"`
	Region Region `json:"region"`

	// UpdatedTime The date and time that the image was last updated.
	UpdatedTime time.Time `json:"updated_time"`

	// Version The image version.
	Version string `json:"version"`
}

// ImageArchitecture defines model for ImageArchitecture.
type ImageArchitecture string

// ImageSpecificationFamily Specifies the image to use by its family name.
type ImageSpecificationFamily struct {
	// Family The family name of the image.
	Family string `json:"family"`
}

// ImageSpecificationID Specifies the image to use by its unique identifier.
type ImageSpecificationID struct {
	Id string `json:"id"`
}

// Instance Detailed information about the instance.
type Instance struct {
	Actions InstanceActionAvailability `json:"actions"`

	// FileSystemMounts The filesystems, along with the mount paths, mounted to
	// the instances. If no filesystems are mounted, this parameter
	// will be missing from the response.
	FileSystemMounts *[]FilesystemMountEntry `json:"file_system_mounts,omitempty"`

	// FileSystemNames The names of the filesystems mounted to the instance. If no filesystems are mounted, this array is empty.
	FileSystemNames []string `json:"file_system_names"`

	// Hostname The hostname assigned to this instance, which resolves to the instance's IP.
	Hostname *string `json:"hostname,omitempty"`

	// Id The unique identifier of the instance.
	Id           string       `json:"id"`
	InstanceType InstanceType `json:"instance_type"`

	// Ip The public IPv4 address of the instance.
	Ip *string `json:"ip,omitempty"`

	// JupyterToken The secret token used to log into the JupyterLab server hosted on the instance.
	JupyterToken *string `json:"jupyter_token,omitempty"`

	// JupyterUrl The URL that opens the JupyterLab environment on the instance.
	JupyterUrl *string `json:"jupyter_url,omitempty"`

	// Name If set, the user-provided name of the instance.
	Name *string `json:"name,omitempty"`

	// PrivateIp The private IPv4 address of the instance.
	PrivateIp *string `json:"private_ip,omitempty"`
	Region    Region  `json:"region"`

	// SshKeyNames The names of the SSH keys that are allowed to access the instance.
	SshKeyNames []string `json:"ssh_key_names"`

	// Status The current status of the instance.
	Status InstanceStatus `json:"status"`

	// Tags Key/value pairs representing the instance's tags.
	Tags *[]TagEntry `json:"tags,omitempty"`
}

// InstanceActionAvailability defines model for InstanceActionAvailability.
type InstanceActionAvailability struct {
	ColdReboot InstanceActionAvailabilityDetails `json:"cold_reboot"`
	Migrate    InstanceActionAvailabilityDetails `json:"migrate"`
	Rebuild    InstanceActionAvailabilityDetails `json:"rebuild"`
	Restart    InstanceActionAvailabilityDetails `json:"restart"`
	Terminate  InstanceActionAvailabilityDetails `json:"terminate"`
}

// InstanceActionAvailabilityDetails defines model for InstanceActionAvailabilityDetails.
type InstanceActionAvailabilityDetails struct {
	// Available If set, indicates that the relevant operation can be performed on the instance in its current state.
	Available bool `json:"available"`

	// ReasonCode A code representing the instance state that is blocking the operation. Only provided if the operation is blocked.
	ReasonCode *InstanceActionAvailabilityDetails_ReasonCode `json:"reason_code,omitempty"`

	// ReasonDescription A longer description of why this operation is currently blocked. Only provided if the operation is blocked.
	ReasonDescription *string `json:"reason_description,omitempty"`
}

// InstanceActionAvailabilityDetailsReasonCode1 defines model for .
type InstanceActionAvailabilityDetailsReasonCode1 = string

// InstanceActionAvailabilityDetails_ReasonCode A code representing the instance state that is blocking the operation. Only provided if the operation is blocked.
type InstanceActionAvailabilityDetails_ReasonCode struct {
	union json.RawMessage
}

// InstanceActionUnavailableCode defines model for InstanceActionUnavailableCode.
type InstanceActionUnavailableCode string

// InstanceLaunchRequest defines model for InstanceLaunchRequest.
type InstanceLaunchRequest struct {
	// FileSystemMounts The filesystem mounts to mount to the instance. When specified alongside
	// `file_system_names`, any filesystems referred to in both lists will use the
	// mount path specified in `file_system_mounts`, rather than the default.
	FileSystemMounts *[]RequestedFilesystemMountEntry `json:"file_system_mounts,omitempty"`

	// FileSystemNames The names of the filesystems you want to mount to the instance. When specified
	// alongside `file_system_mounts`, any filesystems referred to in both lists will use the
	// mount path specified in `file_system_mounts`, rather than the default.
	FileSystemNames *[]string `json:"file_system_names,omitempty"`

	// Hostname The hostname to assign to the instance. If not specified, a default, IP-address-based
	// hostname is assigned. This hostname is driven into /etc/hostname on the instance.
	Hostname *string `json:"hostname,omitempty"`

	// Image The machine image you want to use. Defaults to the latest Lambda Stack image.
	Image *InstanceLaunchRequest_Image `json:"image,omitempty"`

	// InstanceTypeName The type of instance you want to launch. To retrieve a list of available instance types, see
	// [List available instance types](#get-/api/v1/instance-types).
	InstanceTypeName string `json:"instance_type_name"`

	// Name The name you want to assign to your instance. Must be 64 characters or fewer.
	Name       *string          `json:"name,omitempty"`
	RegionName PublicRegionCode `json:"region_name"`

	// SshKeyNames The names of the SSH keys you want to use to provide access to the instance.
	// Currently, exactly one SSH key must be specified.
	SshKeyNames []string `json:"ssh_key_names"`

	// Tags Key/value pairs representing the instance's tags.
	Tags *[]RequestedTagEntry `json:"tags,omitempty"`

	// UserData An instance configuration string specified in a valid
	// [cloud-init user-data](https://cloudinit.readthedocs.io/en/latest/explanation/format.html)
	// format. You can use this field to configure your instance on launch. The
	// user data string must be plain text and cannot exceed 1MB in size.
	UserData *string `json:"user_data,omitempty"`
}

// InstanceLaunchRequest_Image The machine image you want to use. Defaults to the latest Lambda Stack image.
type InstanceLaunchRequest_Image struct {
	union json.RawMessage
}

// InstanceLaunchResponse defines model for InstanceLaunchResponse.
type InstanceLaunchResponse struct {
	// InstanceIds The unique identifiers (IDs) of the launched instances.
	InstanceIds []string `json:"instance_ids"`
}

// InstanceModificationRequest defines model for InstanceModificationRequest.
type InstanceModificationRequest struct {
	// Name The new, user-provided name for the instance.
	Name *string `json:"name,omitempty"`
}

// InstanceRestartRequest defines model for InstanceRestartRequest.
type InstanceRestartRequest struct {
	// InstanceIds The unique identifiers (IDs) of the instances to restart.
	InstanceIds []string `json:"instance_ids"`
}

// InstanceRestartResponse defines model for InstanceRestartResponse.
type InstanceRestartResponse struct {
	// RestartedInstances The list of instances that were successfully restarted.
	RestartedInstances []Instance `json:"restarted_instances"`
}

// InstanceStatus The current status of the instance.
type InstanceStatus string

// InstanceTerminateRequest defines model for InstanceTerminateRequest.
type InstanceTerminateRequest struct {
	// InstanceIds The unique identifiers (IDs) of the instances to terminate.
	InstanceIds []string `json:"instance_ids"`
}

// InstanceTerminateResponse defines model for InstanceTerminateResponse.
type InstanceTerminateResponse struct {
	// TerminatedInstances The list of instances that were successfully terminated.
	TerminatedInstances []Instance `json:"terminated_instances"`
}

// InstanceType defines model for InstanceType.
type InstanceType struct {
	// Description A description of the instance type.
	Description string `json:"description"`

	// GpuDescription The type of GPU used by this instance type.
	GpuDescription string `json:"gpu_description"`

	// Name The name of the instance type.
	Name string `json:"name"`

	// PriceCentsPerHour The price of the instance type in US cents per hour.
	PriceCentsPerHour int               `json:"price_cents_per_hour"`
	Specs             InstanceTypeSpecs `json:"specs"`
}

// InstanceTypeSpecs defines model for InstanceTypeSpecs.
type InstanceTypeSpecs struct {
	// Gpus The number of GPUs.
	Gpus int `json:"gpus"`

	// MemoryGib The amount of RAM in gibibytes (GiB).
	MemoryGib int `json:"memory_gib"`

	// StorageGib The amount of storage in gibibytes (GiB).
	StorageGib int `json:"storage_gib"`

	// Vcpus The number of virtual CPUs.
	Vcpus int `json:"vcpus"`
}

// InstanceTypes defines model for InstanceTypes.
type InstanceTypes map[string]InstanceTypesItem

// InstanceTypesItem Detailed information and regional availability for the instance type.
type InstanceTypesItem struct {
	InstanceType InstanceType `json:"instance_type"`

	// RegionsWithCapacityAvailable A list of the regions in which this instance type is available.
	RegionsWithCapacityAvailable []Region `json:"regions_with_capacity_available"`
}

// NetworkProtocol defines model for NetworkProtocol.
type NetworkProtocol string

// PublicRegionCode defines model for PublicRegionCode.
type PublicRegionCode string

// Region defines model for Region.
type Region struct {
	// Description The location represented by the region code.
	Description string           `json:"description"`
	Name        PublicRegionCode `json:"name"`
}

// RequestedFilesystemMountEntry The mount point for a filesystem mounted to an instance.
type RequestedFilesystemMountEntry struct {
	// FileSystemId The id of the filesystem to mount to the instance.
	FileSystemId string `json:"file_system_id"`

	// MountPoint The absolute path indicating where on the instance the filesystem will be mounted.
	MountPoint string `json:"mount_point"`
}

// RequestedTagEntry defines model for RequestedTagEntry.
type RequestedTagEntry struct {
	// Key The key of the tag.
	Key string `json:"key"`

	// Value The value of the tag.
	Value string `json:"value"`
}

// SSHKey Information about a stored SSH key, which can be used to access instances over
// SSH.
type SSHKey struct {
	// Id The unique identifier (ID) of the SSH key.
	Id string `json:"id"`

	// Name The name of the SSH key.
	Name string `json:"name"`

	// PublicKey The public key for the SSH key.
	PublicKey string `json:"public_key"`
}

// TagEntry defines model for TagEntry.
type TagEntry struct {
	// Key The key of the tag.
	Key string `json:"key"`

	// Value The value of the tag.
	Value string `json:"value"`
}

// FirewallRulesSetJSONRequestBody defines body for FirewallRulesSet for application/json ContentType.
type FirewallRulesSetJSONRequestBody = FirewallRulesPutRequest

// LaunchInstanceJSONRequestBody defines body for LaunchInstance for application/json ContentType.
type LaunchInstanceJSONRequestBody = InstanceLaunchRequest

// RestartInstanceJSONRequestBody defines body for RestartInstance for application/json ContentType.
type RestartInstanceJSONRequestBody = InstanceRestartRequest

// TerminateInstanceJSONRequestBody defines body for TerminateInstance for application/json ContentType.
type TerminateInstanceJSONRequestBody = InstanceTerminateRequest

// PostInstanceJSONRequestBody defines body for PostInstance for application/json ContentType.
type PostInstanceJSONRequestBody = InstanceModificationRequest

// AddSSHKeyJSONRequestBody defines body for AddSSHKey for application/json ContentType.
type AddSSHKeyJSONRequestBody = AddSSHKeyRequest

// AsInstanceActionUnavailableCode returns the union data inside the InstanceActionAvailabilityDetails_ReasonCode as a InstanceActionUnavailableCode
func (t InstanceActionAvailabilityDetails_ReasonCode) AsInstanceActionUnavailableCode() (InstanceActionUnavailableCode, error) {
	var body InstanceActionUnavailableCode
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceActionUnavailableCode overwrites any union data inside the InstanceActionAvailabilityDetails_ReasonCode as the provided InstanceActionUnavailableCode
func (t *InstanceActionAvailabilityDetails_ReasonCode) FromInstanceActionUnavailableCode(v InstanceActionUnavailableCode) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceActionUnavailableCode performs a merge with any union data inside the InstanceActionAvailabilityDetails_ReasonCode, using the provided InstanceActionUnavailableCode
func (t *InstanceActionAvailabilityDetails_ReasonCode) MergeInstanceActionUnavailableCode(v InstanceActionUnavailableCode) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstanceActionAvailabilityDetailsReasonCode1 returns the union data inside the InstanceActionAvailabilityDetails_ReasonCode as a InstanceActionAvailabilityDetailsReasonCode1
func (t InstanceActionAvailabilityDetails_ReasonCode) AsInstanceActionAvailabilityDetailsReasonCode1() (InstanceActionAvailabilityDetailsReasonCode1, error) {
	var body InstanceActionAvailabilityDetailsReasonCode1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceActionAvailabilityDetailsReasonCode1 overwrites any union data inside the InstanceActionAvailabilityDetails_ReasonCode as the provided InstanceActionAvailabilityDetailsReasonCode1
func (t *InstanceActionAvailabilityDetails_ReasonCode) FromInstanceActionAvailabilityDetailsReasonCode1(v InstanceActionAvailabilityDetailsReasonCode1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceActionAvailabilityDetailsReasonCode1 performs a merge with any union data inside the InstanceActionAvailabilityDetails_ReasonCode, using the provided InstanceActionAvailabilityDetailsReasonCode1
func (t *InstanceActionAvailabilityDetails_ReasonCode) MergeInstanceActionAvailabilityDetailsReasonCode1(v InstanceActionAvailabilityDetailsReasonCode1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t InstanceActionAvailabilityDetails_ReasonCode) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *InstanceActionAvailabilityDetails_ReasonCode) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsImageSpecificationID returns the union data inside the InstanceLaunchRequest_Image as a ImageSpecificationID
func (t InstanceLaunchRequest_Image) AsImageSpecificationID() (ImageSpecificationID, error) {
	var body ImageSpecificationID
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageSpecificationID overwrites any union data inside the InstanceLaunchRequest_Image as the provided ImageSpecificationID
func (t *InstanceLaunchRequest_Image) FromImageSpecificationID(v ImageSpecificationID) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageSpecificationID performs a merge with any union data inside the InstanceLaunchRequest_Image, using the provided ImageSpecificationID
func (t *InstanceLaunchRequest_Image) MergeImageSpecificationID(v ImageSpecificationID) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageSpecificationFamily returns the union data inside the InstanceLaunchRequest_Image as a ImageSpecificationFamily
func (t InstanceLaunchRequest_Image) AsImageSpecificationFamily() (ImageSpecificationFamily, error) {
	var body ImageSpecificationFamily
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageSpecificationFamily overwrites any union data inside the InstanceLaunchRequest_Image as the provided ImageSpecificationFamily
func (t *InstanceLaunchRequest_Image) FromImageSpecificationFamily(v ImageSpecificationFamily) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageSpecificationFamily performs a merge with any union data inside the InstanceLaunchRequest_Image, using the provided ImageSpecificationFamily
func (t *InstanceLaunchRequest_Image) MergeImageSpecificationFamily(v ImageSpecificationFamily) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t InstanceLaunchRequest_Image) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *InstanceLaunchRequest_Image) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// FirewallRulesList request
	FirewallRulesList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FirewallRulesSetWithBody request with any body
	FirewallRulesSetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	FirewallRulesSet(ctx context.Context, body FirewallRulesSetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListImages request
	ListImages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LaunchInstanceWithBody request with any body
	LaunchInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LaunchInstance(ctx context.Context, body LaunchInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RestartInstanceWithBody request with any body
	RestartInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RestartInstance(ctx context.Context, body RestartInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TerminateInstanceWithBody request with any body
	TerminateInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TerminateInstance(ctx context.Context, body TerminateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListInstanceTypes request
	ListInstanceTypes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListInstances request
	ListInstances(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetInstance request
	GetInstance(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostInstanceWithBody request with any body
	PostInstanceWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostInstance(ctx context.Context, id string, body PostInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSSHKeys request
	ListSSHKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddSSHKeyWithBody request with any body
	AddSSHKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddSSHKey(ctx context.Context, body AddSSHKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteSSHKey request
	DeleteSSHKey(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) FirewallRulesList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFirewallRulesListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FirewallRulesSetWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFirewallRulesSetRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FirewallRulesSet(ctx context.Context, body FirewallRulesSetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFirewallRulesSetRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListImages(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListImagesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LaunchInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLaunchInstanceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LaunchInstance(ctx context.Context, body LaunchInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLaunchInstanceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RestartInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRestartInstanceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RestartInstance(ctx context.Context, body RestartInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRestartInstanceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TerminateInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTerminateInstanceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TerminateInstance(ctx context.Context, body TerminateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTerminateInstanceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListInstanceTypes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListInstanceTypesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListInstances(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListInstancesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetInstance(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInstanceRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostInstanceWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostInstanceRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostInstance(ctx context.Context, id string, body PostInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostInstanceRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSSHKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSSHKeysRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddSSHKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddSSHKeyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddSSHKey(ctx context.Context, body AddSSHKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddSSHKeyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteSSHKey(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSSHKeyRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewFirewallRulesListRequest generates requests for FirewallRulesList
func NewFirewallRulesListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/firewall-rules")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFirewallRulesSetRequest calls the generic FirewallRulesSet builder with application/json body
func NewFirewallRulesSetRequest(server string, body FirewallRulesSetJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFirewallRulesSetRequestWithBody(server, "application/json", bodyReader)
}

// NewFirewallRulesSetRequestWithBody generates requests for FirewallRulesSet with any type of body
func NewFirewallRulesSetRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/firewall-rules")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListImagesRequest generates requests for ListImages
func NewListImagesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/images")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLaunchInstanceRequest calls the generic LaunchInstance builder with application/json body
func NewLaunchInstanceRequest(server string, body LaunchInstanceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLaunchInstanceRequestWithBody(server, "application/json", bodyReader)
}

// NewLaunchInstanceRequestWithBody generates requests for LaunchInstance with any type of body
func NewLaunchInstanceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/instance-operations/launch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRestartInstanceRequest calls the generic RestartInstance builder with application/json body
func NewRestartInstanceRequest(server string, body RestartInstanceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRestartInstanceRequestWithBody(server, "application/json", bodyReader)
}

// NewRestartInstanceRequestWithBody generates requests for RestartInstance with any type of body
func NewRestartInstanceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/instance-operations/restart")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTerminateInstanceRequest calls the generic TerminateInstance builder with application/json body
func NewTerminateInstanceRequest(server string, body TerminateInstanceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTerminateInstanceRequestWithBody(server, "application/json", bodyReader)
}

// NewTerminateInstanceRequestWithBody generates requests for TerminateInstance with any type of body
func NewTerminateInstanceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/instance-operations/terminate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListInstanceTypesRequest generates requests for ListInstanceTypes
func NewListInstanceTypesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/instance-types")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListInstancesRequest generates requests for ListInstances
func NewListInstancesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/instances")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetInstanceRequest generates requests for GetInstance
func NewGetInstanceRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/instances/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostInstanceRequest calls the generic PostInstance builder with application/json body
func NewPostInstanceRequest(server string, id string, body PostInstanceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostInstanceRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPostInstanceRequestWithBody generates requests for PostInstance with any type of body
func NewPostInstanceRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/instances/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListSSHKeysRequest generates requests for ListSSHKeys
func NewListSSHKeysRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/ssh-keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddSSHKeyRequest calls the generic AddSSHKey builder with application/json body
func NewAddSSHKeyRequest(server string, body AddSSHKeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddSSHKeyRequestWithBody(server, "application/json", bodyReader)
}

// NewAddSSHKeyRequestWithBody generates requests for AddSSHKey with any type of body
func NewAddSSHKeyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/ssh-keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteSSHKeyRequest generates requests for DeleteSSHKey
func NewDeleteSSHKeyRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/ssh-keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// FirewallRulesListWithResponse request
	FirewallRulesListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FirewallRulesListResponse, error)

	// FirewallRulesSetWithBodyWithResponse request with any body
	FirewallRulesSetWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FirewallRulesSetResponse, error)

	FirewallRulesSetWithResponse(ctx context.Context, body FirewallRulesSetJSONRequestBody, reqEditors ...RequestEditorFn) (*FirewallRulesSetResponse, error)

	// ListImagesWithResponse request
	ListImagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListImagesResponse, error)

	// LaunchInstanceWithBodyWithResponse request with any body
	LaunchInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LaunchInstanceResponse, error)

	LaunchInstanceWithResponse(ctx context.Context, body LaunchInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*LaunchInstanceResponse, error)

	// RestartInstanceWithBodyWithResponse request with any body
	RestartInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RestartInstanceResponse, error)

	RestartInstanceWithResponse(ctx context.Context, body RestartInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*RestartInstanceResponse, error)

	// TerminateInstanceWithBodyWithResponse request with any body
	TerminateInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TerminateInstanceResponse, error)

	TerminateInstanceWithResponse(ctx context.Context, body TerminateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*TerminateInstanceResponse, error)

	// ListInstanceTypesWithResponse request
	ListInstanceTypesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListInstanceTypesResponse, error)

	// ListInstancesWithResponse request
	ListInstancesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListInstancesResponse, error)

	// GetInstanceWithResponse request
	GetInstanceWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetInstanceResponse, error)

	// PostInstanceWithBodyWithResponse request with any body
	PostInstanceWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostInstanceResponse, error)

	PostInstanceWithResponse(ctx context.Context, id string, body PostInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*PostInstanceResponse, error)

	// ListSSHKeysWithResponse request
	ListSSHKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSSHKeysResponse, error)

	// AddSSHKeyWithBodyWithResponse request with any body
	AddSSHKeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddSSHKeyResponse, error)

	AddSSHKeyWithResponse(ctx context.Context, body AddSSHKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*AddSSHKeyResponse, error)

	// DeleteSSHKeyWithResponse request
	DeleteSSHKeyWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteSSHKeyResponse, error)
}

type FirewallRulesListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []FirewallRule `json:"data"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r FirewallRulesListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FirewallRulesListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FirewallRulesSetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []FirewallRule `json:"data"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r FirewallRulesSetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FirewallRulesSetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListImagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []Image `json:"data"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r ListImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LaunchInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data InstanceLaunchResponse `json:"data"`
	}
	JSON400 *struct {
		Error LaunchInstance_400_Error `json:"error"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error LaunchInstance_403_Error `json:"error"`
	}
	JSON404 *struct {
		Error ApiErrorLaunchResourceNotFound `json:"error"`
	}
}
type LaunchInstance_400_Error struct {
	union json.RawMessage
}
type LaunchInstance_403_Error struct {
	union json.RawMessage
}

// Status returns HTTPResponse.Status
func (r LaunchInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LaunchInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RestartInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data InstanceRestartResponse `json:"data"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
	JSON404 *struct {
		Error ApiErrorInstanceNotFound `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r RestartInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RestartInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TerminateInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data InstanceTerminateResponse `json:"data"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
	JSON404 *struct {
		Error ApiErrorInstanceNotFound `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r TerminateInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TerminateInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListInstanceTypesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data InstanceTypes `json:"data"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r ListInstanceTypesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListInstanceTypesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListInstancesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []Instance `json:"data"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r ListInstancesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListInstancesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Data Detailed information about the instance.
		Data Instance `json:"data"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
	JSON404 *struct {
		Error ApiErrorInstanceNotFound `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r GetInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Data Detailed information about the instance.
		Data Instance `json:"data"`
	}
	JSON400 *struct {
		Error ApiErrorInvalidParameters `json:"error"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
	JSON404 *struct {
		Error ApiErrorInstanceNotFound `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r PostInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSSHKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []SSHKey `json:"data"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r ListSSHKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSSHKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddSSHKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data AddSSHKey_200_Data `json:"data"`
	}
	JSON400 *struct {
		Error ApiErrorInvalidParameters `json:"error"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
}
type AddSSHKey_200_Data struct {
	union json.RawMessage
}

// Status returns HTTPResponse.Status
func (r AddSSHKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddSSHKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteSSHKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data EmptyResponse `json:"data"`
	}
	JSON400 *struct {
		Error ApiErrorInvalidParameters `json:"error"`
	}
	JSON401 *struct {
		Error ApiErrorUnauthorized `json:"error"`
	}
	JSON403 *struct {
		Error ApiErrorAccountInactive `json:"error"`
	}
}

// Status returns HTTPResponse.Status
func (r DeleteSSHKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteSSHKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// FirewallRulesListWithResponse request returning *FirewallRulesListResponse
func (c *ClientWithResponses) FirewallRulesListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FirewallRulesListResponse, error) {
	rsp, err := c.FirewallRulesList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFirewallRulesListResponse(rsp)
}

// FirewallRulesSetWithBodyWithResponse request with arbitrary body returning *FirewallRulesSetResponse
func (c *ClientWithResponses) FirewallRulesSetWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FirewallRulesSetResponse, error) {
	rsp, err := c.FirewallRulesSetWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFirewallRulesSetResponse(rsp)
}

func (c *ClientWithResponses) FirewallRulesSetWithResponse(ctx context.Context, body FirewallRulesSetJSONRequestBody, reqEditors ...RequestEditorFn) (*FirewallRulesSetResponse, error) {
	rsp, err := c.FirewallRulesSet(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFirewallRulesSetResponse(rsp)
}

// ListImagesWithResponse request returning *ListImagesResponse
func (c *ClientWithResponses) ListImagesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListImagesResponse, error) {
	rsp, err := c.ListImages(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListImagesResponse(rsp)
}

// LaunchInstanceWithBodyWithResponse request with arbitrary body returning *LaunchInstanceResponse
func (c *ClientWithResponses) LaunchInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LaunchInstanceResponse, error) {
	rsp, err := c.LaunchInstanceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLaunchInstanceResponse(rsp)
}

func (c *ClientWithResponses) LaunchInstanceWithResponse(ctx context.Context, body LaunchInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*LaunchInstanceResponse, error) {
	rsp, err := c.LaunchInstance(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLaunchInstanceResponse(rsp)
}

// RestartInstanceWithBodyWithResponse request with arbitrary body returning *RestartInstanceResponse
func (c *ClientWithResponses) RestartInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RestartInstanceResponse, error) {
	rsp, err := c.RestartInstanceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRestartInstanceResponse(rsp)
}

func (c *ClientWithResponses) RestartInstanceWithResponse(ctx context.Context, body RestartInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*RestartInstanceResponse, error) {
	rsp, err := c.RestartInstance(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRestartInstanceResponse(rsp)
}

// TerminateInstanceWithBodyWithResponse request with arbitrary body returning *TerminateInstanceResponse
func (c *ClientWithResponses) TerminateInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TerminateInstanceResponse, error) {
	rsp, err := c.TerminateInstanceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTerminateInstanceResponse(rsp)
}

func (c *ClientWithResponses) TerminateInstanceWithResponse(ctx context.Context, body TerminateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*TerminateInstanceResponse, error) {
	rsp, err := c.TerminateInstance(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTerminateInstanceResponse(rsp)
}

// ListInstanceTypesWithResponse request returning *ListInstanceTypesResponse
func (c *ClientWithResponses) ListInstanceTypesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListInstanceTypesResponse, error) {
	rsp, err := c.ListInstanceTypes(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListInstanceTypesResponse(rsp)
}

// ListInstancesWithResponse request returning *ListInstancesResponse
func (c *ClientWithResponses) ListInstancesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListInstancesResponse, error) {
	rsp, err := c.ListInstances(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListInstancesResponse(rsp)
}

// GetInstanceWithResponse request returning *GetInstanceResponse
func (c *ClientWithResponses) GetInstanceWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetInstanceResponse, error) {
	rsp, err := c.GetInstance(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInstanceResponse(rsp)
}

// PostInstanceWithBodyWithResponse request with arbitrary body returning *PostInstanceResponse
func (c *ClientWithResponses) PostInstanceWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostInstanceResponse, error) {
	rsp, err := c.PostInstanceWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostInstanceResponse(rsp)
}

func (c *ClientWithResponses) PostInstanceWithResponse(ctx context.Context, id string, body PostInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*PostInstanceResponse, error) {
	rsp, err := c.PostInstance(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostInstanceResponse(rsp)
}

// ListSSHKeysWithResponse request returning *ListSSHKeysResponse
func (c *ClientWithResponses) ListSSHKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSSHKeysResponse, error) {
	rsp, err := c.ListSSHKeys(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSSHKeysResponse(rsp)
}

// AddSSHKeyWithBodyWithResponse request with arbitrary body returning *AddSSHKeyResponse
func (c *ClientWithResponses) AddSSHKeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddSSHKeyResponse, error) {
	rsp, err := c.AddSSHKeyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddSSHKeyResponse(rsp)
}

func (c *ClientWithResponses) AddSSHKeyWithResponse(ctx context.Context, body AddSSHKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*AddSSHKeyResponse, error) {
	rsp, err := c.AddSSHKey(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddSSHKeyResponse(rsp)
}

// DeleteSSHKeyWithResponse request returning *DeleteSSHKeyResponse
func (c *ClientWithResponses) DeleteSSHKeyWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteSSHKeyResponse, error) {
	rsp, err := c.DeleteSSHKey(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteSSHKeyResponse(rsp)
}

// ParseFirewallRulesListResponse parses an HTTP response from a FirewallRulesListWithResponse call
func ParseFirewallRulesListResponse(rsp *http.Response) (*FirewallRulesListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FirewallRulesListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []FirewallRule `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseFirewallRulesSetResponse parses an HTTP response from a FirewallRulesSetWithResponse call
func ParseFirewallRulesSetResponse(rsp *http.Response) (*FirewallRulesSetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FirewallRulesSetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []FirewallRule `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseListImagesResponse parses an HTTP response from a ListImagesWithResponse call
func ParseListImagesResponse(rsp *http.Response) (*ListImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []Image `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseLaunchInstanceResponse parses an HTTP response from a LaunchInstanceWithResponse call
func ParseLaunchInstanceResponse(rsp *http.Response) (*LaunchInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LaunchInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data InstanceLaunchResponse `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error LaunchInstance_400_Error `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error LaunchInstance_403_Error `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error ApiErrorLaunchResourceNotFound `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRestartInstanceResponse parses an HTTP response from a RestartInstanceWithResponse call
func ParseRestartInstanceResponse(rsp *http.Response) (*RestartInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RestartInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data InstanceRestartResponse `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error ApiErrorInstanceNotFound `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseTerminateInstanceResponse parses an HTTP response from a TerminateInstanceWithResponse call
func ParseTerminateInstanceResponse(rsp *http.Response) (*TerminateInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TerminateInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data InstanceTerminateResponse `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error ApiErrorInstanceNotFound `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListInstanceTypesResponse parses an HTTP response from a ListInstanceTypesWithResponse call
func ParseListInstanceTypesResponse(rsp *http.Response) (*ListInstanceTypesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListInstanceTypesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data InstanceTypes `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseListInstancesResponse parses an HTTP response from a ListInstancesWithResponse call
func ParseListInstancesResponse(rsp *http.Response) (*ListInstancesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListInstancesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []Instance `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseGetInstanceResponse parses an HTTP response from a GetInstanceWithResponse call
func ParseGetInstanceResponse(rsp *http.Response) (*GetInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Data Detailed information about the instance.
			Data Instance `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error ApiErrorInstanceNotFound `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostInstanceResponse parses an HTTP response from a PostInstanceWithResponse call
func ParsePostInstanceResponse(rsp *http.Response) (*PostInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Data Detailed information about the instance.
			Data Instance `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error ApiErrorInvalidParameters `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Error ApiErrorInstanceNotFound `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListSSHKeysResponse parses an HTTP response from a ListSSHKeysWithResponse call
func ParseListSSHKeysResponse(rsp *http.Response) (*ListSSHKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSSHKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []SSHKey `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseAddSSHKeyResponse parses an HTTP response from a AddSSHKeyWithResponse call
func ParseAddSSHKeyResponse(rsp *http.Response) (*AddSSHKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddSSHKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data AddSSHKey_200_Data `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error ApiErrorInvalidParameters `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseDeleteSSHKeyResponse parses an HTTP response from a DeleteSSHKeyWithResponse call
func ParseDeleteSSHKeyResponse(rsp *http.Response) (*DeleteSSHKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteSSHKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data EmptyResponse `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Error ApiErrorInvalidParameters `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest struct {
			Error ApiErrorUnauthorized `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Error ApiErrorAccountInactive `json:"error"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}
