---
version: '3'
tasks:
  all:
    desc: Run all linting and formatting checks
    cmds:
      - task: go
      - task: markdown
      - task: shell
      - task: github-actions
  go:
    desc: Lint and format Go code
    cmds: [golangci-lint run ./..., gofumpt -l -d .]
  go-fix:
    desc: Fix Go code formatting
    cmds: [gofumpt -l -w ., go mod tidy]
  yaml:
    desc: Check YAML files for compliance
    cmds:
      - mise exec -- yamlfix --config-file .yamlfix.toml --exclude "chart/templates/*" --check .
  yaml-fix:
    desc: Fix YAML formatting
    cmds:
      - mise exec -- yamlfix --config-file .yamlfix.toml --exclude "chart/templates/*"
        .
  markdown:
    desc: Lint Markdown files
    cmds: [markdownlint-cli **/*.md]
  shell:
    desc: Lint shell scripts
    cmds:
      - find . -name "*.sh" -exec shellcheck {} +
      - find . -name "*.sh" -exec shfmt -d {} +
  shell-fix:
    desc: Fix shell script formatting
    cmds: ['find . -name "*.sh" -exec shfmt -w {} +']
  github-actions:
    desc: Lint GitHub Actions workflows
    cmds: [actionlint]
  fix-all:
    desc: Auto-fix all formatting issues
    cmds:
      - task: go-fix
      - task: yaml-fix
      - task: shell-fix
      - echo "All formatting applied! Review changes before committing."
