version: '3'

tasks:

  generate:
    desc: Generate code (deepcopy methods, CRDs, etc.)
    cmds:
      - go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest
      - $(go env GOPATH)/bin/controller-gen object paths="./pkg/api/..."
      - $(go env GOPATH)/bin/controller-gen crd paths="./pkg/api/..." output:crd:artifacts:config=config/crd/bases

  build:
    desc: Build the manager binary
    deps: [generate]
    cmds:
      - go build -o bin/manager ./cmd/manager

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - go clean -cache