---
version: '3'
tasks:
  install-codegen:
    desc: Ensure code generation tools are available via go.mod
    cmds:
      - go mod download
    status: [go list -f '{{.Dir}}' -m sigs.k8s.io/controller-tools > /dev/null 2>&1]
  generate-providers:
    desc: Generate provider API clients from OpenAPI/GraphQL specs
    deps: [install-codegen]
    cmds:
      - echo "No provider API clients to generate - using native SDKs"
  generate:
    desc: Generate code (deepcopy methods, CRDs, and provider clients)
    deps: [install-codegen]
    cmds:
      - go run sigs.k8s.io/controller-tools/cmd/controller-gen object paths="./pkg/api/..."
      - go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths="./pkg/api/..." output:crd:artifacts:config=config/crd/bases
      - task: generate-providers
  build:
    desc: Build the manager binary
    deps: [generate]
    cmds: [go build -o bin/manager ./cmd/manager]
  lint:
    desc: Run linters
    cmds: [golangci-lint run ./...]
  clean:
    desc: Clean build artifacts
    cmds: [rm -rf bin/, go clean -cache]
