version: '3'

tasks:

  generate:
    desc: Generate code (deepcopy methods, etc.)
    cmds:
      - go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest
      - controller-gen object paths="./pkg/api/..."

  build:
    desc: Build the manager binary
    deps: [generate]
    cmds:
      - go build -o bin/manager ./cmd/manager

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - go clean -cache