---
version: '3'
tasks:
  all:
    desc: Run all security scans
    cmds:
      - task: gosec
      - task: trivy-code
      - task: trivy-container
      - task: dependencies
      - task: licenses
  gosec:
    desc: Run Go security scanner
    cmds:
      - go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest
      - gosec -fmt sarif -out gosec-results.sarif ./... || true
      - gosec ./...
  trivy-code:
    desc: Scan code for vulnerabilities
    cmds: ['trivy fs --severity HIGH,CRITICAL .']
  trivy-container:
    desc: Scan container image for vulnerabilities
    cmds:
      - docker build -t tgp-operator:security-scan .
      - trivy image --severity HIGH,CRITICAL tgp-operator:security-scan
  trivy:
    desc: Run all Trivy scans (code and container)
    cmds:
      - task: trivy-code
      - task: trivy-container
  dependencies:
    desc: Check for vulnerable dependencies
    cmds: [go list -json -deps ./... | nancy sleuth]
  licenses:
    desc: Check dependency licenses
    cmds:
      - go-licenses check ./... --disallowed_types=forbidden,restricted || true
      - echo "Review any license issues above"
  fix:
    desc: Auto-fix security issues where possible
    cmds:
      - go get -u ./...
      - go mod tidy
      - echo "Updated dependencies. Run 'task security:all' to recheck."
